# Backup of /etc/pacman.conf (sanitized, no system-managed metadata)

[options]
HoldPkg     = pacman glibc
Architecture = auto

# Misc options
Color
ILoveCandy
VerbosePkgLists
DisableDownloadTimeout
ParallelDownloads = 12
DownloadUser = alpm

SigLevel    = Required DatabaseOptional
LocalFileSigLevel = Optional

# CachyOS repositories
[cachyos-v3]
Include = /etc/pacman.d/cachyos-v3-mirrorlist

[cachyos-core-v3]
Include = /etc/pacman.d/cachyos-v3-mirrorlist

[cachyos-extra-v3]
Include = /etc/pacman.d/cachyos-v3-mirrorlist

[cachyos]
Include = /etc/pacman.d/cachyos-mirrorlist

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

[multilib]
Include = /etc/pacman.d/mirrorlist

